// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4N6UtAH9nib2sSccsr7g_Ej8Y0CqR-YE',
    appId: '1:369191586213:web:d1800c8267374a0ba0804c',
    messagingSenderId: '369191586213',
    projectId: 'sunny-childhood',
    authDomain: 'sunny-childhood.firebaseapp.com',
    databaseURL: 'https://sunny-childhood-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-childhood.appspot.com',
    measurementId: 'G-GNR16K9NHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAD3fMjXFvXAI8aEdRCyKV5fYxmh2FR94',
    appId: '1:369191586213:android:4b86d5d4ecb25589a0804c',
    messagingSenderId: '369191586213',
    projectId: 'sunny-childhood',
    databaseURL: 'https://sunny-childhood-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-childhood.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATiH_58u72SfE7n0dfYQZhJEn9zjk2lBk',
    appId: '1:369191586213:ios:6ddea9e9cf5572a2a0804c',
    messagingSenderId: '369191586213',
    projectId: 'sunny-childhood',
    databaseURL: 'https://sunny-childhood-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-childhood.appspot.com',
    iosBundleId: 'com.example.sunnyChildhood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATiH_58u72SfE7n0dfYQZhJEn9zjk2lBk',
    appId: '1:369191586213:ios:6ddea9e9cf5572a2a0804c',
    messagingSenderId: '369191586213',
    projectId: 'sunny-childhood',
    databaseURL: 'https://sunny-childhood-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-childhood.appspot.com',
    iosBundleId: 'com.example.sunnyChildhood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4N6UtAH9nib2sSccsr7g_Ej8Y0CqR-YE',
    appId: '1:369191586213:web:67467281f6bd64dca0804c',
    messagingSenderId: '369191586213',
    projectId: 'sunny-childhood',
    authDomain: 'sunny-childhood.firebaseapp.com',
    databaseURL: 'https://sunny-childhood-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sunny-childhood.appspot.com',
    measurementId: 'G-J1YFYSZ7H5',
  );
}
